services:
  postgres:
    image: postgres:16-alpine
    # ...

  redis:
    image: redis:7-alpine
    # ...

  server:
    build: ./server
    ports:
      - "4000:4000"
    depends_on: [postgres, redis]

  client:
    build:
      context: ./client-vite     # ← 指向新的目录
      dockerfile: Dockerfile
    depends_on: [server]
    ports:
      - "3000:80"
